// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: multipart/multipart.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package multipart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Multipart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ptr           []uint64               `protobuf:"varint,1,rep,packed,name=ptr,proto3" json:"ptr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Multipart) Reset() {
	*x = Multipart{}
	mi := &file_multipart_multipart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Multipart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Multipart) ProtoMessage() {}

func (x *Multipart) ProtoReflect() protoreflect.Message {
	mi := &file_multipart_multipart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Multipart.ProtoReflect.Descriptor instead.
func (*Multipart) Descriptor() ([]byte, []int) {
	return file_multipart_multipart_proto_rawDescGZIP(), []int{0}
}

func (x *Multipart) GetPtr() []uint64 {
	if x != nil {
		return x.Ptr
	}
	return nil
}

var File_multipart_multipart_proto protoreflect.FileDescriptor

const file_multipart_multipart_proto_rawDesc = "" +
	"\n" +
	"\x19multipart/multipart.proto\x12\x11alchemy.multipart\"\x1d\n" +
	"\tMultipart\x12\x10\n" +
	"\x03ptr\x18\x01 \x03(\x04R\x03ptrB\xb0\x01\n" +
	"\x15com.alchemy.multipartB\x0eMultipartProtoP\x01Z\"github.com/wjiec/alchemy/multipart\xa2\x02\x03AMX\xaa\x02\x11Alchemy.Multipart\xca\x02\x11Alchemy\\Multipart\xe2\x02\x1dAlchemy\\Multipart\\GPBMetadata\xea\x02\x12Alchemy::Multipartb\x06proto3"

var (
	file_multipart_multipart_proto_rawDescOnce sync.Once
	file_multipart_multipart_proto_rawDescData []byte
)

func file_multipart_multipart_proto_rawDescGZIP() []byte {
	file_multipart_multipart_proto_rawDescOnce.Do(func() {
		file_multipart_multipart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipart_multipart_proto_rawDesc), len(file_multipart_multipart_proto_rawDesc)))
	})
	return file_multipart_multipart_proto_rawDescData
}

var file_multipart_multipart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multipart_multipart_proto_goTypes = []any{
	(*Multipart)(nil), // 0: alchemy.multipart.Multipart
}
var file_multipart_multipart_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multipart_multipart_proto_init() }
func file_multipart_multipart_proto_init() {
	if File_multipart_multipart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipart_multipart_proto_rawDesc), len(file_multipart_multipart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipart_multipart_proto_goTypes,
		DependencyIndexes: file_multipart_multipart_proto_depIdxs,
		MessageInfos:      file_multipart_multipart_proto_msgTypes,
	}.Build()
	File_multipart_multipart_proto = out.File
	file_multipart_multipart_proto_goTypes = nil
	file_multipart_multipart_proto_depIdxs = nil
}
