// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bizerr/pberr/pberr.proto

package pberr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithHttpStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpCode      uint32                 `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithHttpStatus) Reset() {
	*x = WithHttpStatus{}
	mi := &file_bizerr_pberr_pberr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithHttpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithHttpStatus) ProtoMessage() {}

func (x *WithHttpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bizerr_pberr_pberr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithHttpStatus.ProtoReflect.Descriptor instead.
func (*WithHttpStatus) Descriptor() ([]byte, []int) {
	return file_bizerr_pberr_pberr_proto_rawDescGZIP(), []int{0}
}

func (x *WithHttpStatus) GetHttpCode() uint32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

type WithCause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CauseError    string                 `protobuf:"bytes,1,opt,name=cause_error,json=causeError,proto3" json:"cause_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithCause) Reset() {
	*x = WithCause{}
	mi := &file_bizerr_pberr_pberr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithCause) ProtoMessage() {}

func (x *WithCause) ProtoReflect() protoreflect.Message {
	mi := &file_bizerr_pberr_pberr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithCause.ProtoReflect.Descriptor instead.
func (*WithCause) Descriptor() ([]byte, []int) {
	return file_bizerr_pberr_pberr_proto_rawDescGZIP(), []int{1}
}

func (x *WithCause) GetCauseError() string {
	if x != nil {
		return x.CauseError
	}
	return ""
}

var File_bizerr_pberr_pberr_proto protoreflect.FileDescriptor

const file_bizerr_pberr_pberr_proto_rawDesc = "" +
	"\n" +
	"\x18bizerr/pberr/pberr.proto\x12\x14alchemy.bizerr.pberr\"-\n" +
	"\x0eWithHttpStatus\x12\x1b\n" +
	"\thttp_code\x18\x01 \x01(\rR\bhttpCode\",\n" +
	"\tWithCause\x12\x1f\n" +
	"\vcause_error\x18\x01 \x01(\tR\n" +
	"causeErrorB\xbf\x01\n" +
	"\x18com.alchemy.bizerr.pberrB\n" +
	"PberrProtoP\x01Z%github.com/wjiec/alchemy/bizerr/pberr\xa2\x02\x03ABP\xaa\x02\x14Alchemy.Bizerr.Pberr\xca\x02\x14Alchemy\\Bizerr\\Pberr\xe2\x02 Alchemy\\Bizerr\\Pberr\\GPBMetadata\xea\x02\x16Alchemy::Bizerr::Pberrb\x06proto3"

var (
	file_bizerr_pberr_pberr_proto_rawDescOnce sync.Once
	file_bizerr_pberr_pberr_proto_rawDescData []byte
)

func file_bizerr_pberr_pberr_proto_rawDescGZIP() []byte {
	file_bizerr_pberr_pberr_proto_rawDescOnce.Do(func() {
		file_bizerr_pberr_pberr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bizerr_pberr_pberr_proto_rawDesc), len(file_bizerr_pberr_pberr_proto_rawDesc)))
	})
	return file_bizerr_pberr_pberr_proto_rawDescData
}

var file_bizerr_pberr_pberr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bizerr_pberr_pberr_proto_goTypes = []any{
	(*WithHttpStatus)(nil), // 0: alchemy.bizerr.pberr.WithHttpStatus
	(*WithCause)(nil),      // 1: alchemy.bizerr.pberr.WithCause
}
var file_bizerr_pberr_pberr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bizerr_pberr_pberr_proto_init() }
func file_bizerr_pberr_pberr_proto_init() {
	if File_bizerr_pberr_pberr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bizerr_pberr_pberr_proto_rawDesc), len(file_bizerr_pberr_pberr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bizerr_pberr_pberr_proto_goTypes,
		DependencyIndexes: file_bizerr_pberr_pberr_proto_depIdxs,
		MessageInfos:      file_bizerr_pberr_pberr_proto_msgTypes,
	}.Build()
	File_bizerr_pberr_pberr_proto = out.File
	file_bizerr_pberr_pberr_proto_goTypes = nil
	file_bizerr_pberr_pberr_proto_depIdxs = nil
}
