// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/testpb/proto3.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH
// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proto3Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NestedValue    *Proto3Message         `protobuf:"bytes,999,opt,name=nested_value,json=nestedValue,proto3" json:"nested_value,omitempty"`
	StringValue    string                 `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	Int32Value     int32                  `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value     int64                  `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	BoolValue      bool                   `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	FloatValue     float32                `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue    float64                `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	RepeatedString []string               `protobuf:"bytes,7,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedInt32  []string               `protobuf:"bytes,8,rep,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Proto3Message) Reset() {
	*x = Proto3Message{}
	mi := &file_internal_testpb_proto3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto3Message) ProtoMessage() {}

func (x *Proto3Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testpb_proto3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto3Message.ProtoReflect.Descriptor instead.
func (*Proto3Message) Descriptor() ([]byte, []int) {
	return file_internal_testpb_proto3_proto_rawDescGZIP(), []int{0}
}

func (x *Proto3Message) GetNestedValue() *Proto3Message {
	if x != nil {
		return x.NestedValue
	}
	return nil
}

func (x *Proto3Message) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *Proto3Message) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *Proto3Message) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *Proto3Message) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *Proto3Message) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *Proto3Message) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *Proto3Message) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *Proto3Message) GetRepeatedInt32() []string {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

var File_internal_testpb_proto3_proto protoreflect.FileDescriptor

const file_internal_testpb_proto3_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/testpb/proto3.proto\x12\x1dalchemy.codec.internal.testpb\"\xf9\x02\n" +
	"\rProto3Message\x12P\n" +
	"\fnested_value\x18\xe7\a \x01(\v2,.alchemy.codec.internal.testpb.Proto3MessageR\vnestedValue\x12!\n" +
	"\fstring_value\x18\x01 \x01(\tR\vstringValue\x12\x1f\n" +
	"\vint32_value\x18\x02 \x01(\x05R\n" +
	"int32Value\x12\x1f\n" +
	"\vint64_value\x18\x03 \x01(\x03R\n" +
	"int64Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bR\tboolValue\x12\x1f\n" +
	"\vfloat_value\x18\x05 \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x06 \x01(\x01R\vdoubleValue\x12'\n" +
	"\x0frepeated_string\x18\a \x03(\tR\x0erepeatedString\x12%\n" +
	"\x0erepeated_int32\x18\b \x03(\tR\rrepeatedInt32B\xf2\x01\n" +
	"!com.alchemy.codec.internal.testpbB\vProto3ProtoP\x01Z(github.com/wjiec/alchemy/internal/testpb\xa2\x02\x04ACIT\xaa\x02\x1dAlchemy.Codec.Internal.Testpb\xca\x02\x1dAlchemy\\Codec\\Internal\\Testpb\xe2\x02)Alchemy\\Codec\\Internal\\Testpb\\GPBMetadata\xea\x02 Alchemy::Codec::Internal::Testpbb\x06proto3"

var (
	file_internal_testpb_proto3_proto_rawDescOnce sync.Once
	file_internal_testpb_proto3_proto_rawDescData []byte
)

func file_internal_testpb_proto3_proto_rawDescGZIP() []byte {
	file_internal_testpb_proto3_proto_rawDescOnce.Do(func() {
		file_internal_testpb_proto3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testpb_proto3_proto_rawDesc), len(file_internal_testpb_proto3_proto_rawDesc)))
	})
	return file_internal_testpb_proto3_proto_rawDescData
}

var file_internal_testpb_proto3_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_testpb_proto3_proto_goTypes = []any{
	(*Proto3Message)(nil), // 0: alchemy.codec.internal.testpb.Proto3Message
}
var file_internal_testpb_proto3_proto_depIdxs = []int32{
	0, // 0: alchemy.codec.internal.testpb.Proto3Message.nested_value:type_name -> alchemy.codec.internal.testpb.Proto3Message
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_testpb_proto3_proto_init() }
func file_internal_testpb_proto3_proto_init() {
	if File_internal_testpb_proto3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testpb_proto3_proto_rawDesc), len(file_internal_testpb_proto3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testpb_proto3_proto_goTypes,
		DependencyIndexes: file_internal_testpb_proto3_proto_depIdxs,
		MessageInfos:      file_internal_testpb_proto3_proto_msgTypes,
	}.Build()
	File_internal_testpb_proto3_proto = out.File
	file_internal_testpb_proto3_proto_goTypes = nil
	file_internal_testpb_proto3_proto_depIdxs = nil
}
